# Generated by Django 5.2.11 on 2026-03-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.academicyear'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.division'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.branch')),
            ],
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='board.subject'),
        ),
    ]
