# Generated by Django 5.2.11 on 2026-03-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_academicyear_division_studentprofile_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('teacher_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.branch')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.division')),
            ],
        ),
    ]
