# Generated by Django 5.2.11 on 2026-03-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_liveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
