# Generated by Django 5.2.11 on 2026-03-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_liveclass_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='board_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
