# Generated by Django 5.2.11 on 2026-03-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='notify_type',
            field=models.CharField(default='direct', max_length=20),
        ),
    ]
