# Generated by Django 5.2.11 on 2026-05-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_liveclass_notify_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_email',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='teacher_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['live_class', 'is_active'], name='board_atten_live_cl_7766e3_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['branch', 'academic_year', 'division', 'is_active'], name='board_livec_branch__f705eb_idx'),
        ),
    ]
